services:
  - type: web
    name: todo-api
    env: go
    buildCommand: go build -o main ./cmd/main.go
    startCommand: migrate -path db/migrations -database $DATABASE_URL up && ./main
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: todo-db
          property: connectionString
